// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/report_uc.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/report_uc.go -destination=internal/mocks/mock_report_uc.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ports "KolinFinance/internal/ports"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockReportUseCase is a mock of ReportUseCase interface.
type MockReportUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockReportUseCaseMockRecorder
	isgomock struct{}
}

// MockReportUseCaseMockRecorder is the mock recorder for MockReportUseCase.
type MockReportUseCaseMockRecorder struct {
	mock *MockReportUseCase
}

// NewMockReportUseCase creates a new mock instance.
func NewMockReportUseCase(ctrl *gomock.Controller) *MockReportUseCase {
	mock := &MockReportUseCase{ctrl: ctrl}
	mock.recorder = &MockReportUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportUseCase) EXPECT() *MockReportUseCaseMockRecorder {
	return m.recorder
}

// Balance mocks base method.
func (m *MockReportUseCase) Balance(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Balance indicates an expected call of Balance.
func (mr *MockReportUseCaseMockRecorder) Balance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*MockReportUseCase)(nil).Balance), ctx)
}

// ReportByPeriod mocks base method.
func (m *MockReportUseCase) ReportByPeriod(ctx context.Context, from, to time.Time) (ports.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportByPeriod", ctx, from, to)
	ret0, _ := ret[0].(ports.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportByPeriod indicates an expected call of ReportByPeriod.
func (mr *MockReportUseCaseMockRecorder) ReportByPeriod(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportByPeriod", reflect.TypeOf((*MockReportUseCase)(nil).ReportByPeriod), ctx, from, to)
}
